CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	role TEXT NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'STAFF')),
	password_hash TEXT NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	unit TEXT NOT NULL,
	quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
	min_quantity INTEGER NOT NULL DEFAULT 0 CHECK (min_quantity >= 0),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menu_items (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menu_item_ingredients (
	menu_item_id TEXT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
	ingredient_id TEXT NOT NULL REFERENCES inventory(id),
	amount INTEGER NOT NULL CHECK (amount > 0),
	PRIMARY KEY (menu_item_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS orders (
	id TEXT PRIMARY KEY,
	code TEXT NOT NULL UNIQUE,
	total NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
	status TEXT NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
	note TEXT,
	created_by TEXT NOT NULL REFERENCES users(id),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
	menu_item_id TEXT NOT NULL REFERENCES menu_items(id),
	name TEXT NOT NULL,
	quantity INTEGER NOT NULL CHECK (quantity > 0),
	unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
	total NUMERIC(12, 2) NOT NULL CHECK (total >= 0)
);

CREATE TABLE IF NOT EXISTS sessions (
	token TEXT PRIMARY KEY,
	user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
